server:
  port: 8081


spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/springData
    username: root
    password: talal12345
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    hostname: localhost